---
# tasks file for ansible-aide


- name: install aide package
  yum:
    name: aide
    state: present
  tags: install

- name: Copy aide config (costum)
  template:
    src: config/costum_aide.conf.j2
    dest: "{{aide_config_file}}"
    backup: yes
  when: aide_costum_config is defined and aide_costum_config 
  tags: conf

- name: Copy aide config (complete)
  template:
    src: config/aide.conf.j2
    dest: "{{aide_config_file}}"
    #backup: yes
  when: aide_costum_config is not defined or not aide_costum_config
  tags: conf

- name: initilize aide db
  command: /sbin/aide --init -c "{{aide_config_file}}"
  tags: init,db

- name: move db file
  command: /bin/cp "{{aide_db_dir}}"/aide.db.new.gz "{{aide_db_dir}}"/aide.db.gz
  tags: db

- template:
    src: scripts/aidecheck.sh.j2
    dest: "/usr/local/bin/aidecheck.sh"
    mode: '0744'
  when: check is defined and check
  tags: check,script

- name:  Add crontab to check integrity nightly
  cron:
    name: "{{item.name | default('Aide check for every 59 min')}}"
    hour: "{{item.hour | default('omit')}}"
    minute: "{{item.minute | default('59')}}"
    day: "{{item.day | default('omit')}}"
    month: "{{item.month | default('omit')}}"
    weekday: "{{item.weekday | default('omit')}}"
    job: "{{item.job | default('/usr/local/bin/aidecheck.sh')}}"
    state: "{{item.state | default('present')}}"
    user: "{{item.user | default('omit')}}"
    cron_file: "{{item.cron_file | default('omit')}}"
  with_items:
   - "{{ aide_cron_job }}" 
  tags: cron,check
  when: check is defined and check
