---
# tasks file for ansible-aide


- name: install aide package
  yum:
    name: aide
    state: present
  tags: install

- template:
    src: config/costum_aide.conf.j2
    dest: "{{config_file}}"
  when: costum_config is defined and costum_config 
  tags: conf

- name: initilize aide db
  command: /sbin/aide --init -c "{{config_file}}"
  tags: init,db

- debug:
    var: db_dir
  tags: deb

- name: move db file
  command: /bin/cp "{{db_dir}}"/aide.db.new.gz "{{db_dir}}"/aide.db.gz
  tags: db

- template:
    src: scripts/aidechk.sh.j2
    dest: "/usr/local/bin/aidecheck.sh"
    mode: '0744'
  when: check is defined and check
  tags: check

- name:  Add crontab to check integrity nightly
  cron:
    name: "nightly check"
    hour: "01"
    minute: "0"
    job: "/usr/local/bin/aidecheck.sh" 
  tags: cron,check
